export type { Icon, IconProps, IconWeight } from "./types";
export { ICON_WEIGHT, ICON_WEIGHT_LINEAR, ICON_WEIGHT_BOLD } from "./types";
export { Plus } from "./plus";
export { DotsThreeVertical } from "./dots-three-vertical";

export {
  Widget as SquaresFour,
  UsersGroupTwoRounded as Users,
  FileText,
  RefreshCircle as ArrowCounterClockwise,
  Archive,
  Settings as Gear,
  Shield,
  Upload as UploadSimple,
  Filter as Funnel,
  Lightning,
  ArrowLeft,
  ArrowRight,
  CheckRead as Check,
  CloseCircle as X,
  AltArrowDown as CaretDown,
  AltArrowUp as CaretUp,
  Wallet,
  SquareTopDown as ArrowUpRight,
  Restart as ArrowsClockwise,
  Letter as EnvelopeSimple,
  Plain as PaperPlaneTilt,
  Bag as ShoppingBag,
  ClockCircle as Clock,
  ShieldCheck,
  ShieldWarning,
  Eye,
  Download as DownloadSimple,
  Ghost as Skull,
  Confetti,
  Like as ThumbsUp,
  Chart2 as ChartBar,
  CodeFile as TerminalWindow,
  SidebarMinimalistic as SidebarSimple,
  Copy as CopySimple,
  MapPoint as MapPin,
  DangerCircle as WarningCircle,
  CloseCircle as XCircle,
  DangerTriangle as Warning,
  UsersGroupRounded as UsersThree,
  CalendarMark as CalendarCheck,
  Pen as PencilSimple,
  AddSquare,
  AddCircle as PlusCircle,
  TrashBinTrash as Trash,
  MenuDots as DotsThree,
  SortVertical as ArrowsDownUp,
  GraphUp as TrendUp,
  GraphDown as TrendDown,
  ForbiddenCircle as Prohibit,
  CheckCircle,
  PlugCircle as PlugsConnected,
  Power,
  ArrowUp,
  ArrowDown,
  Phone,
  List,
} from "@solar-icons/react";
