// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/partner-dashboard/MetricsBannerFeed.tsx": () => import("../components/mockups/partner-dashboard/MetricsBannerFeed.tsx"),
  "./components/mockups/partner-dashboard/SplitPanelCommand.tsx": () => import("../components/mockups/partner-dashboard/SplitPanelCommand.tsx"),
  "./components/mockups/partner-dashboard/TopNavWideGrid.tsx": () => import("../components/mockups/partner-dashboard/TopNavWideGrid.tsx")
};
